// Generated by Universal Protocol Runtime. Do not edit by hand.
//
// Encode/decode is provided by the dependency-free runtime package, driven by
// the schema descriptors below. Frames are byte-compatible with the C++ and
// Python runtimes.

import { Codec } from "../dist/index.js";
import type { Protocol } from "../dist/index.js";

export const PROTOCOL_NAME = "general_direct_codec";
export const PROTOCOL_FINGERPRINT = "3723055222363272718";

export const PROTOCOL: Protocol = {
  name: "general_direct_codec",
  fingerprint: "3723055222363272718",
  structs: [
    {
      name: "Inner",
      isMessage: false,
      minimumSize: 6,
      allowTrailingBytes: false,
      dispatchPrefix: new Uint8Array([]),
      fields: [
        { id: 0, name: "a", kind: "unsigned", widthBytes: 2, byteOrder: "little_endian", stringEncoding: "ascii", fixedSize: 0, dynamicSize: false, sizeFromField: 0, structId: 0, alignment: 1, isReserved: false, reservedFillByte: 0, fixedCount: 0, dynamicCount: false, countFromField: 0, hasCondition: false, conditionField: 0, conditionEquals: 0, hasPresence: false, presenceField: 0, presenceBit: 0, tagFromField: 0, variantCases: [], hasExpectedUnsigned: false, expectedUnsigned: 0 },
        { id: 1, name: "b", kind: "unsigned", widthBytes: 4, byteOrder: "little_endian", stringEncoding: "ascii", fixedSize: 0, dynamicSize: false, sizeFromField: 0, structId: 0, alignment: 1, isReserved: false, reservedFillByte: 0, fixedCount: 0, dynamicCount: false, countFromField: 0, hasCondition: false, conditionField: 0, conditionEquals: 0, hasPresence: false, presenceField: 0, presenceBit: 0, tagFromField: 0, variantCases: [], hasExpectedUnsigned: false, expectedUnsigned: 0 },
      ],
      checksums: [
      ],
    },
    {
      name: "Pair",
      isMessage: false,
      minimumSize: 8,
      allowTrailingBytes: false,
      dispatchPrefix: new Uint8Array([]),
      fields: [
        { id: 0, name: "key", kind: "unsigned", widthBytes: 2, byteOrder: "little_endian", stringEncoding: "ascii", fixedSize: 0, dynamicSize: false, sizeFromField: 0, structId: 0, alignment: 1, isReserved: false, reservedFillByte: 0, fixedCount: 0, dynamicCount: false, countFromField: 0, hasCondition: false, conditionField: 0, conditionEquals: 0, hasPresence: false, presenceField: 0, presenceBit: 0, tagFromField: 0, variantCases: [], hasExpectedUnsigned: false, expectedUnsigned: 0 },
        { id: 1, name: "value", kind: "struct", widthBytes: 0, byteOrder: "little_endian", stringEncoding: "ascii", fixedSize: 6, dynamicSize: false, sizeFromField: 0, structId: 0, alignment: 1, isReserved: false, reservedFillByte: 0, fixedCount: 0, dynamicCount: false, countFromField: 0, hasCondition: false, conditionField: 0, conditionEquals: 0, hasPresence: false, presenceField: 0, presenceBit: 0, tagFromField: 0, variantCases: [], hasExpectedUnsigned: false, expectedUnsigned: 0 },
      ],
      checksums: [
      ],
    },
    {
      name: "QuoteDetail",
      isMessage: false,
      minimumSize: 8,
      allowTrailingBytes: false,
      dispatchPrefix: new Uint8Array([]),
      fields: [
        { id: 0, name: "bid", kind: "unsigned", widthBytes: 4, byteOrder: "little_endian", stringEncoding: "ascii", fixedSize: 0, dynamicSize: false, sizeFromField: 0, structId: 0, alignment: 1, isReserved: false, reservedFillByte: 0, fixedCount: 0, dynamicCount: false, countFromField: 0, hasCondition: false, conditionField: 0, conditionEquals: 0, hasPresence: false, presenceField: 0, presenceBit: 0, tagFromField: 0, variantCases: [], hasExpectedUnsigned: false, expectedUnsigned: 0 },
        { id: 1, name: "ask", kind: "unsigned", widthBytes: 4, byteOrder: "little_endian", stringEncoding: "ascii", fixedSize: 0, dynamicSize: false, sizeFromField: 0, structId: 0, alignment: 1, isReserved: false, reservedFillByte: 0, fixedCount: 0, dynamicCount: false, countFromField: 0, hasCondition: false, conditionField: 0, conditionEquals: 0, hasPresence: false, presenceField: 0, presenceBit: 0, tagFromField: 0, variantCases: [], hasExpectedUnsigned: false, expectedUnsigned: 0 },
      ],
      checksums: [
      ],
    },
    {
      name: "TradeDetail",
      isMessage: false,
      minimumSize: 8,
      allowTrailingBytes: false,
      dispatchPrefix: new Uint8Array([]),
      fields: [
        { id: 0, name: "trade_id", kind: "unsigned", widthBytes: 8, byteOrder: "little_endian", stringEncoding: "ascii", fixedSize: 0, dynamicSize: false, sizeFromField: 0, structId: 0, alignment: 1, isReserved: false, reservedFillByte: 0, fixedCount: 0, dynamicCount: false, countFromField: 0, hasCondition: false, conditionField: 0, conditionEquals: 0, hasPresence: false, presenceField: 0, presenceBit: 0, tagFromField: 0, variantCases: [], hasExpectedUnsigned: false, expectedUnsigned: 0 },
      ],
      checksums: [
      ],
    },
  ],
  messages: [
    {
      name: "Book",
      isMessage: true,
      minimumSize: 4,
      allowTrailingBytes: false,
      dispatchPrefix: new Uint8Array([0x01]),
      fields: [
        { id: 0, name: "message_type", kind: "unsigned", widthBytes: 1, byteOrder: "little_endian", stringEncoding: "ascii", fixedSize: 0, dynamicSize: false, sizeFromField: 0, structId: 0, alignment: 1, isReserved: false, reservedFillByte: 0, fixedCount: 0, dynamicCount: false, countFromField: 0, hasCondition: false, conditionField: 0, conditionEquals: 0, hasPresence: false, presenceField: 0, presenceBit: 0, tagFromField: 0, variantCases: [], hasExpectedUnsigned: true, expectedUnsigned: 1 },
        { id: 1, name: "count", kind: "unsigned", widthBytes: 1, byteOrder: "little_endian", stringEncoding: "ascii", fixedSize: 0, dynamicSize: false, sizeFromField: 0, structId: 0, alignment: 1, isReserved: false, reservedFillByte: 0, fixedCount: 0, dynamicCount: false, countFromField: 0, hasCondition: false, conditionField: 0, conditionEquals: 0, hasPresence: false, presenceField: 0, presenceBit: 0, tagFromField: 0, variantCases: [], hasExpectedUnsigned: false, expectedUnsigned: 0 },
        { id: 2, name: "pairs", kind: "collection", widthBytes: 0, byteOrder: "little_endian", stringEncoding: "ascii", fixedSize: 0, dynamicSize: false, sizeFromField: 0, structId: 1, alignment: 1, isReserved: false, reservedFillByte: 0, fixedCount: 0, dynamicCount: true, countFromField: 1, hasCondition: false, conditionField: 0, conditionEquals: 0, hasPresence: false, presenceField: 0, presenceBit: 0, tagFromField: 0, variantCases: [], hasExpectedUnsigned: false, expectedUnsigned: 0 },
        { id: 3, name: "checksum", kind: "unsigned", widthBytes: 2, byteOrder: "little_endian", stringEncoding: "ascii", fixedSize: 0, dynamicSize: false, sizeFromField: 0, structId: 0, alignment: 1, isReserved: false, reservedFillByte: 0, fixedCount: 0, dynamicCount: false, countFromField: 0, hasCondition: false, conditionField: 0, conditionEquals: 0, hasPresence: false, presenceField: 0, presenceBit: 0, tagFromField: 0, variantCases: [], hasExpectedUnsigned: false, expectedUnsigned: 0 },
      ],
      checksums: [
        { fieldId: 3, resultWidthBytes: 2, algorithmName: "sum16", fromAnchor: { kind: "frame_start", fieldId: 0 }, toAnchor: { kind: "before_self", fieldId: 3 } },
      ],
    },
    {
      name: "Event",
      isMessage: true,
      minimumSize: 10,
      allowTrailingBytes: false,
      dispatchPrefix: new Uint8Array([0x02]),
      fields: [
        { id: 0, name: "message_type", kind: "unsigned", widthBytes: 1, byteOrder: "little_endian", stringEncoding: "ascii", fixedSize: 0, dynamicSize: false, sizeFromField: 0, structId: 0, alignment: 1, isReserved: false, reservedFillByte: 0, fixedCount: 0, dynamicCount: false, countFromField: 0, hasCondition: false, conditionField: 0, conditionEquals: 0, hasPresence: false, presenceField: 0, presenceBit: 0, tagFromField: 0, variantCases: [], hasExpectedUnsigned: true, expectedUnsigned: 2 },
        { id: 1, name: "kind", kind: "unsigned", widthBytes: 1, byteOrder: "little_endian", stringEncoding: "ascii", fixedSize: 0, dynamicSize: false, sizeFromField: 0, structId: 0, alignment: 1, isReserved: false, reservedFillByte: 0, fixedCount: 0, dynamicCount: false, countFromField: 0, hasCondition: false, conditionField: 0, conditionEquals: 0, hasPresence: false, presenceField: 0, presenceBit: 0, tagFromField: 0, variantCases: [], hasExpectedUnsigned: false, expectedUnsigned: 0 },
        { id: 2, name: "detail", kind: "variant", widthBytes: 0, byteOrder: "little_endian", stringEncoding: "ascii", fixedSize: 8, dynamicSize: false, sizeFromField: 0, structId: 0, alignment: 1, isReserved: false, reservedFillByte: 0, fixedCount: 0, dynamicCount: false, countFromField: 0, hasCondition: false, conditionField: 0, conditionEquals: 0, hasPresence: false, presenceField: 0, presenceBit: 0, tagFromField: 1, variantCases: [{ tagValue: 1, structId: 2 }, { tagValue: 2, structId: 3 }], hasExpectedUnsigned: false, expectedUnsigned: 0 },
      ],
      checksums: [
      ],
    },
    {
      name: "Note",
      isMessage: true,
      minimumSize: 2,
      allowTrailingBytes: false,
      dispatchPrefix: new Uint8Array([0x03]),
      fields: [
        { id: 0, name: "message_type", kind: "unsigned", widthBytes: 1, byteOrder: "little_endian", stringEncoding: "ascii", fixedSize: 0, dynamicSize: false, sizeFromField: 0, structId: 0, alignment: 1, isReserved: false, reservedFillByte: 0, fixedCount: 0, dynamicCount: false, countFromField: 0, hasCondition: false, conditionField: 0, conditionEquals: 0, hasPresence: false, presenceField: 0, presenceBit: 0, tagFromField: 0, variantCases: [], hasExpectedUnsigned: true, expectedUnsigned: 3 },
        { id: 1, name: "presence", kind: "unsigned", widthBytes: 1, byteOrder: "little_endian", stringEncoding: "ascii", fixedSize: 0, dynamicSize: false, sizeFromField: 0, structId: 0, alignment: 1, isReserved: false, reservedFillByte: 0, fixedCount: 0, dynamicCount: false, countFromField: 0, hasCondition: false, conditionField: 0, conditionEquals: 0, hasPresence: false, presenceField: 0, presenceBit: 0, tagFromField: 0, variantCases: [], hasExpectedUnsigned: false, expectedUnsigned: 0 },
        { id: 2, name: "note_len", kind: "unsigned", widthBytes: 1, byteOrder: "little_endian", stringEncoding: "ascii", fixedSize: 0, dynamicSize: false, sizeFromField: 0, structId: 0, alignment: 1, isReserved: false, reservedFillByte: 0, fixedCount: 0, dynamicCount: false, countFromField: 0, hasCondition: false, conditionField: 0, conditionEquals: 0, hasPresence: true, presenceField: 1, presenceBit: 0, tagFromField: 0, variantCases: [], hasExpectedUnsigned: false, expectedUnsigned: 0 },
        { id: 3, name: "note", kind: "string", widthBytes: 0, byteOrder: "little_endian", stringEncoding: "utf8", fixedSize: 0, dynamicSize: true, sizeFromField: 2, structId: 0, alignment: 1, isReserved: false, reservedFillByte: 0, fixedCount: 0, dynamicCount: false, countFromField: 0, hasCondition: false, conditionField: 0, conditionEquals: 0, hasPresence: true, presenceField: 1, presenceBit: 0, tagFromField: 0, variantCases: [], hasExpectedUnsigned: false, expectedUnsigned: 0 },
      ],
      checksums: [
      ],
    },
  ],
};

export const CODEC = new Codec(PROTOCOL);

export interface Inner {
  a?: number;
  b?: number;
}

export const Inner = {
  fields: {
    a: 0,
    b: 1,
  } as const,
  encode(value: Inner): Uint8Array { return CODEC.encode("Inner", value); },
  decode(frame: Uint8Array): Inner { return CODEC.decode("Inner", frame) as unknown as Inner; },
  decodeSequence(frame: Uint8Array): Inner[] { return CODEC.decodeSequence("Inner", frame) as unknown as Inner[]; },
};

export interface Pair {
  key?: number;
  value?: Inner;
}

export const Pair = {
  fields: {
    key: 0,
    value: 1,
  } as const,
  encode(value: Pair): Uint8Array { return CODEC.encode("Pair", value); },
  decode(frame: Uint8Array): Pair { return CODEC.decode("Pair", frame) as unknown as Pair; },
  decodeSequence(frame: Uint8Array): Pair[] { return CODEC.decodeSequence("Pair", frame) as unknown as Pair[]; },
};

export interface QuoteDetail {
  bid?: number;
  ask?: number;
}

export const QuoteDetail = {
  fields: {
    bid: 0,
    ask: 1,
  } as const,
  encode(value: QuoteDetail): Uint8Array { return CODEC.encode("QuoteDetail", value); },
  decode(frame: Uint8Array): QuoteDetail { return CODEC.decode("QuoteDetail", frame) as unknown as QuoteDetail; },
  decodeSequence(frame: Uint8Array): QuoteDetail[] { return CODEC.decodeSequence("QuoteDetail", frame) as unknown as QuoteDetail[]; },
};

export interface TradeDetail {
  trade_id?: number | bigint;
}

export const TradeDetail = {
  fields: {
    trade_id: 0,
  } as const,
  encode(value: TradeDetail): Uint8Array { return CODEC.encode("TradeDetail", value); },
  decode(frame: Uint8Array): TradeDetail { return CODEC.decode("TradeDetail", frame) as unknown as TradeDetail; },
  decodeSequence(frame: Uint8Array): TradeDetail[] { return CODEC.decodeSequence("TradeDetail", frame) as unknown as TradeDetail[]; },
};

export interface Book {
  message_type?: number;
  count?: number;
  pairs?: Pair[];
  checksum?: number;
}

export const Book = {
  fields: {
    message_type: 0,
    count: 1,
    pairs: 2,
    checksum: 3,
  } as const,
  encode(value: Book): Uint8Array { return CODEC.encode("Book", value); },
  decode(frame: Uint8Array): Book { return CODEC.decode("Book", frame) as unknown as Book; },
  decodeSequence(frame: Uint8Array): Book[] { return CODEC.decodeSequence("Book", frame) as unknown as Book[]; },
};

export interface Event {
  message_type?: number;
  kind?: number;
  detail?: QuoteDetail | TradeDetail;
}

export const Event = {
  fields: {
    message_type: 0,
    kind: 1,
    detail: 2,
  } as const,
  encode(value: Event): Uint8Array { return CODEC.encode("Event", value); },
  decode(frame: Uint8Array): Event { return CODEC.decode("Event", frame) as unknown as Event; },
  decodeSequence(frame: Uint8Array): Event[] { return CODEC.decodeSequence("Event", frame) as unknown as Event[]; },
};

export interface Note {
  message_type?: number;
  presence?: number;
  note_len?: number;
  note?: string;
}

export const Note = {
  fields: {
    message_type: 0,
    presence: 1,
    note_len: 2,
    note: 3,
  } as const,
  encode(value: Note): Uint8Array { return CODEC.encode("Note", value); },
  decode(frame: Uint8Array): Note { return CODEC.decode("Note", frame) as unknown as Note; },
  decodeSequence(frame: Uint8Array): Note[] { return CODEC.decodeSequence("Note", frame) as unknown as Note[]; },
};
