#!/usr/bin/env python3
"""Regenerates the Python and TypeScript protocol modules used by the examples.

The ``generated/`` folders are intentionally *not* committed to the repository.
Run this script once after a fresh checkout (and again whenever a schema or the
code generator changes) to produce them:

    python3 examples/generate_bindings.py

It drives ``//packages/upr_codegen:upr-gen`` (built via Bazel) for each shared
schema:

* TypeScript modules are written verbatim - they are pure, dependency-free TS.
* Python modules are written and then lightly adapted to use the pure-Python
  ``Codec`` (instead of the native pybind11 extension) so the examples run
  without a C++ build. The wire bytes are identical either way.
"""

from __future__ import annotations

import pathlib
import re
import subprocess
import tempfile

SCHEMAS = ("market_data", "advanced_market_data", "hardware_telemetry")

_REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
_SCHEMA_DIR = _REPO_ROOT / "examples" / "schema"
_PY_OUT = _REPO_ROOT / "examples" / "python" / "generated"
_TS_OUT = _REPO_ROOT / "examples" / "typescript" / "generated"
_GEN_TARGET = "//packages/upr_codegen:upr-gen"
_GEN_BINARY = _REPO_ROOT / "bazel-bin" / "packages" / "upr_codegen" / "generate_bindings"


def build_generator() -> None:
    subprocess.run(["bazel", "build", _GEN_TARGET], cwd=_REPO_ROOT, check=True)


def generate_typescript(schema: str) -> None:
    _TS_OUT.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            str(_GEN_BINARY),
            "--lang", "typescript",
            "--input", str(_SCHEMA_DIR / f"{schema}.upr"),
            "--output", str(_TS_OUT / f"{schema}.ts"),
            "--runtime-import", "universal-protocol-runtime",
        ],
        cwd=_REPO_ROOT,
        check=True,
    )


def _adapt_python_to_pure_codec(text: str, module: str) -> str:
    """Swaps the native-extension codec for the dependency-free ``Codec``."""
    text = text.replace(
        "Encode/decode is provided by the generated pybind11 extension wrapping\n"
        "the C++ direct/static codec. Do not edit by hand.",
        "Encode/decode is driven by the dependency-free Python codec in\n"
        "``universal_protocol_runtime`` using the schema descriptors below. Frames\n"
        "are byte-compatible with the C++ and TypeScript runtimes.\n"
        "\n"
        "Generated by `upr-gen --lang python` and adapted to use the pure-Python\n"
        "``Codec`` so the examples run without building the native extension.",
    )
    text = re.sub(r"^import _%s_native as _native\n" % re.escape(module), "", text, flags=re.M)
    text = re.sub(
        r"class _NativeCodec\(_Codec\):.*?\nCODEC = _NativeCodec\(PROTOCOL\)\n",
        "CODEC = _Codec(PROTOCOL)\n",
        text,
        flags=re.S,
    )
    return text


def generate_python(schema: str) -> None:
    _PY_OUT.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = pathlib.Path(tmp)
        subprocess.run(
            [
                str(_GEN_BINARY),
                "--lang", "python",
                "--input", str(_SCHEMA_DIR / f"{schema}.upr"),
                "--output", str(tmp_path / f"{schema}.py"),
                "--native-output", str(tmp_path / f"_{schema}_native.cpp"),
                "--native-header-output", str(tmp_path / f"{schema}_native.hpp"),
            ],
            cwd=_REPO_ROOT,
            check=True,
        )
        raw = (tmp_path / f"{schema}.py").read_text()
    (_PY_OUT / f"{schema}.py").write_text(_adapt_python_to_pure_codec(raw, schema))


def main() -> int:
    build_generator()
    for schema in SCHEMAS:
        generate_typescript(schema)
        generate_python(schema)
        print(f"generated {schema} (python + typescript)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
